language: csharp

notifications:
  irc:
    channels:
      - "irc.freenode.org#git-tfs"
    template:
      - "travis build %{build_number} (%{branch} - %{commit} - %{author}): %{message} #{build_url}"
    on_success: change
    on_failure: always

install:
  - sudo apt-get install cmake mono-devel mono-gmcs

script:
  - ./script/travis
