#appveyor.yml reference: http://www.appveyor.com/docs/appveyor-yml
image: Visual Studio 2019
clone_folder: c:\gittfs
# build cache to preserve files/folders between builds
cache:
  - src\packages -> src\paket.lock  # preserve "packages" directory in the root of build folder but will reset it if `paket.lock` is modified
init: []
build_script:
- ps: |
    $env:configuration = "Release"
    cd src
    if($env:target -eq $null)
    {
      $target = "AppVeyorBuild"
      echo "target: $target"
      .\build.ps1 -Target "$target" -Configuration $env:configuration -ScriptArgs '-isDryRun=true -gitHubUserAccount"$env:gitHubUserAccount" -gitHubToken="$env:gitHubToken" -chocolateyToken="$env:chocolateyToken"'
    }
    else
    {
      $target = $env:target
      echo "target: $target"
      .\build.ps1 -Target "$target" -Configuration $env:configuration -ScriptArgs '-isDryRun=false -gitHubUserAccount"$env:gitHubUserAccount" -gitHubToken="$env:gitHubToken" -chocolateyToken="$env:chocolateyToken"'
    }

test: off
